services:
  
  user-1:
    build: 
      context: ./user/
    container_name: user-1
    cap_add:
      - NET_ADMIN
    command: sh -c "ip route del default &&
                    ip route add default via 10.5.1.10 &&
                    tail -f /dev/null"
    networks:
      - private
    depends_on:
      - router
  
  user-2:
    build: 
        context: ./user/
    container_name: user-2
    cap_add:
      - NET_ADMIN
    command: sh -c "ip route del default &&
                    ip route add default via 10.5.1.10 &&
                    tail -f /dev/null"
    networks:
      - private
    depends_on:
      - router
  
  web-container:
    build: 
      context: ./web-server/
    container_name: web-server
    cap_add:
      - NET_ADMIN
    command: sh -c "ip route del default &&
                    ip route add default via 10.5.2.10 &&
                    apache2ctl -D FOREGROUND"
    networks:
      - dmz
    ports:
      - 8080:80
    depends_on:
      - router

  router:
    build:
      context: ./user
    container_name: router
    networks:
      dmz :
        ipv4_address: 10.5.2.10
      private :
        ipv4_address: 10.5.1.10
      public:
        ipv4_address: 10.0.0.2
    cap_add:
      - NET_ADMIN 
    command: >-
      sh -c "
      sysctl -w net.ipv4.ip_forward=1 && 
      ip addr add 10.5.2.10/24 dev eth1 && 
      ip addr add 10.5.1.10/24 dev eth0 && 
      iptables -t nat -A POSTROUTING -o eth2 -j MASQUERADE &&
      iptables -t nat -A PREROUTING -i eth2 -p tcp --dport 80 -j DNAT --to-destination 10.5.2.2:80 &&
      tail -f /dev/null"

networks:
  public:
    driver: macvlan
    driver_opts:
      parent : enp0s31f6
    ipam:
     config:
      - subnet: 10.0.0.0/24
  private:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.1.0/24
  dmz:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.2.0/24